#!/bin/bash

python3 scripts/case11/model_form_interp_GPR_ablation_spatial.py
python3 scripts/case11/model_form_interp_GPR_ablation_temp.py
python3 scripts/case11/model_form_interp_IPM_ablation_spatial.py
python3 scripts/case11/model_form_interp_IPM_ablation_temp.py